# Generated by Django 4.1.3 on 2022-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpersonalinformation',
            name='batting_style',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='playerpersonalinformation',
            name='role',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='home_ground',
            field=models.CharField(max_length=50),
        ),
    ]
