# Generated by Django 4.1.3 on 2022-11-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_playerpersonalinformation_batting_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpersonalinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='player/images'),
        ),
    ]
